### ISSUE TITLE
[2주차/이예림] 기본타입간의 호환성

### ISSUE THREAD

**Issue by yarimu** [SOPT-all/35-STUDY-WEB-PEACANG#10]
### 문제

❓ 아래 anyExam 함수에서 변수 타입과 할당에 주목하여, 
각 주석이 달린 코드 줄(1, 2, 3번)에서 오류가 발생하는지 체크하고,
오류가 발생하는 경우에는 그 원인을 설명하고, 
오류가 발생하지 않는 경우에는 왜 오류가 발생하지 않는지 이유를 설명해주세요!

```javascript
function anyExam(){
	let unknownVar: unknown;
	let anyVar: any;
	let undefinedVar: undefined;
	let neverVar: never;	
	
	anyVar = unknownVar; // 1       (O,X)
	undefinedVar = anyVar; // 2    (O,X)
	neverVar = anyVar;     // 3        (O,X)
}
```

**Comment by gonn-i** [comment]
```ts
function anyExam(){
	let unknownVar: unknown;
	let anyVar: any;
	let undefinedVar: undefined;
	let neverVar: never;	
	
	anyVar = unknownVar; // 1      오류 X 
	undefinedVar = anyVar; // 2    오류 X  
	neverVar = anyVar;     // 3    오류 O
```

A1:  오류 X 
` any`는 모든 타입의 슈퍼타입이 될 수도 있고 모든 타입의 서브 타입이 될 수 있기 때문이다.  `unknown` 타입은, `any`를 제외한 그 어떤 타입의 변수에도 할당 불가하다. 

A2:  오류 X  
`any` 모든 타입의 슈퍼타입이 될 수도 있고 모든 타입의 서브 타입이 될 수 있다. `any` 타입은 모든타입으로 다운캐스트 할 수 있고, 또 업캐스트 할 수 있다.

A3:  오류 O  
`never` 는 그 어떠한 타입도 포함하지 않는 집합 공집합이기 떄문에 모든 타입의 서브 타입이다. 따라서, 그 어떤 타입도 네버에 들어갈 수 없다.

**Comment by gwagjiug** [comment]
```typescript
function anyExam(){
	let unknownVar: unknown;
	let anyVar: any;
	let undefinedVar: undefined;
	let neverVar: never;	
	
	anyVar = unknownVar; // 1      오류 X 
	undefinedVar = anyVar; // 2    오류 X  
	neverVar = anyVar;     // 3    오류 O
```
1. `unknown` 타입의 값은 타입이 불분명하긴 하지만, `any` 타입은 모든 타입을 허용하기 때문에 어떤 값도 할당이 가능하다
2. `any` 타입은 모든 타입과 `호환` 된다. 여기서 호환은 모든 타입의 슈퍼타입도, 서브 타입도 될 수 있음을 말한다.
3. `never` 타입은 절대로 발생하지 않는 값을 나타내며 어떠한 값도 `never` 타입 변수에 할당 될 수 없다.

😎😎

**Comment by thisishwarang** [comment]
1,2번은 에러가 발생하지 않는다. any타입은 never를 제외한 모든 타입에 대해 대입할 수도, 대입될 수도 있기 때문이다.
3번은 에러가 발생한다. never 타입은 타입 계층도의 가장 하단에 있기 때문에 다운 캐스팅이 불가능 할 뿐더러 공집합과 같은 개념의 성질을 가지기 때문에 any타입 또한 값을 할당할 수 없다.

**Comment by heesunee** [comment]
```typescript
function anyExam(){
	let unknownVar: unknown;
	let anyVar: any;
	let undefinedVar: undefined;
	let neverVar: never;	
	
	anyVar = unknownVar; // 1       (X)
	undefinedVar = anyVar; // 2    (X)
	neverVar = anyVar;     // 3        (O)
}
```

✔1번: any타입은 모든 타입의 슈퍼타입도, 모든 타입의 서브타임이 될 수도 있습니다. 또한 unknown 타입의 값은 any를 제외한 어떤 타입의 변수에도 할당할 수 없습니다. 
✔ 2번:  any타입은 모든 타입의 슈퍼타입도, 모든 타입의 서브타임이 될 수도 있습니다.
✔ 3번: never타입은 공집합이기 때문에 그 어떤 타입도 never타입으로 다운캐스팅할 수 없습니다.

**Comment by yarimu** [comment]
```javascript
function anyExam(){
	let unknownVar: unknown;
	let anyVar: any;
	let undefinedVar: undefined;
	let neverVar: never;	
	
	anyVar = unknownVar; // 1       (O,X)
	undefinedVar = anyVar; // 2    (O,X)
	neverVar = anyVar;     // 3        (O,X)
}
```
**1. anyVar = unknownVar; // 1**

**결과**:  (X)

**설명**: unknown 타입은 any와 마찬가지로 모든 타입의 값을 가질 수 있지만, any 타입과 다르게 더 제한적이다. unknown을 다른 타입으로 할당하려면 타입을 명시적으로 확인해야 한다. 반대로 unknown 타입을 any 타입에 할당하는 것은 허용된다. 따라서 unknownVar의 값을 anyVar에 할당해도 오류가 발생하지 않는다!

**2. undefinedVar = anyVar; // 2**

**결과**: (X)

**설명**: any 타입은 모든 타입과 호환되므로, undefined 타입의 변수에 any 타입 값을 할당하는 것도 문제가 없다. anyVar에는 undefined가 할당될 수 있으므로, 타입 검사를 통과하여 오류가 발생하지 않는다.

**3. neverVar = anyVar; // 3**

**결과**:  (O)

**설명**: never 타입은 절대 발생하지 않는 값, 즉 어떠한 값도 가질 수 없는 타입이다. any 타입의 값을 never 타입 변수에 할당하는 것은 허용되지 않기 때문에 neverVar = anyVar에서는 오류가 발생한다.
