### ISSUE TITLE
[2주차/곽지욱] 타입 단언과 조건

### ISSUE THREAD

**Issue by gwagjiug** [SOPT-all/35-STUDY-WEB-PEACANG#11]
### 문제

```typescript
type Person = {
  name: string;
  age: number;
};

let person: Person = {};
person.name = "";
person.age = 23;
```

다음과 같은 코드가 있을 때 에러가 발생하게 되는데, 이 에러가 `왜?` 발생하고 `어떻게?` 해결할 수 있나요?

그리고 `어떻게?` 에 해당하는 부분에 조건에 대해서 설명해주세요

**Comment by gonn-i** [comment]
A1: 왜! 
Person타입은 **nam과, age 속성 모두**를 가져야 하는데  `let person: Person = {}; ` 의 경우 초기화를 빈객체로 해주고 있기 때문에 타입 **불일치로 오류**가 발생한다! 

A2: 어떻게 해결?
예제와 같이 당장 초기화할때 빈객체로 두고 싶거나 혹은, , 초과 프로퍼티 검사를 피하고 싶을때는 
**타입 단언**을 사용하면 된다. 

```ts
type Person = {
  name: string;
  age: number;
};

// let person: Person = {};
let person= {}  as Person ; // 타입 단언을 사용하여 문제를 해결 ☀️
person.name = "";
person.age = 23;

```

A3: 타입단언에 대한 조건 
타입단언은 둘중 하나의 조건을 충족해야 사용될 수 있다

>1️⃣ **A가 B의 슈퍼타입**
> 2️⃣ **A가 B의 서브타입**

`let num3 = 10 as string; ` 의 경우, 숫자 타입과 문자열 타입이 서로 슈퍼 - 서브 타입이 아니라 타입 단언이 불가하다!

**Comment by thisishwarang** [comment]
왜? : Person 타입은 필수적으로 name, age 프로퍼티를 필요로 하는데 person 변수를 선언할 때 빈 객체로 초기화했기 때문에 에러가 발생한다.

어떻게? : 
```
let person = {} as Person;
person.name = "";
person.age = 25;
```
위 코드와 같이 Person 타입으로 타입 단언을 해주면 해결할 수 있다.

이때 타입 단언의 조건으로는
A as B 라고 타입 단언을 할 때는
A가 B의 슈퍼타입(부모타입) 이거나, A가 B의 서브타입(자식타입) 이어야 한다.

**Comment by heesunee** [comment]
✔ 에러 발생 원인: 변수 person은 빈 객체로 초기화 되었습니다. 그러나 빈 객체는 Person 타입이 아니기 때문에 오류가 발생합니다.

✔ 해결 방법
```typescript
let person = {} as Person;
person.name = "";
person.age = 23; 
```

값 as 타입으로 특정 값을 원하는 타입으로 단언할 수 있습니다. 빈 객체는 Person 타입이라고 타입스크립트에게 단언해주면 됩니다!

✔ 타입 단언의 조건
A as B 로 표현 했을 때 A가 B의 슈퍼타입이거나 A가 B의 서브타입이어야 합니다.

**Comment by yarimu** [comment]
🅰️1️⃣ 에러 발생 원인
`let person: Person = {};`에서 오류 발생!

Person타입은 name과 age라는 두 가지 속성을 필수로 가진다. 하지만 {}로 초기화 되었고, name, age 속성 모두 없기 때문에 Person타입으로 인정될 수 없다.

🅰️2️⃣ 해결방법
```javascript
let person = {} as Person;
person.name = "";
person.age = 23; 
```

🅰️3️⃣ 타입 단언의 조건
값 as 타입 형식의 단언식을 A as B로 표현했을 때 
`A가 B의 슈퍼타입`, ` A가 B의 서브타입` 두가지 조건 중 한가지를 반드시 만족해야 한다.
