### ISSUE TITLE
[3주차/박희선] 함수 타입 종합 문제

### ISSUE THREAD

**Issue by heesunee** [SOPT-all/35-STUDY-WEB-PEACANG#13]
### 문제

💡Q1. Operation1과 Operation2는 모두 동일한 내용의 함수 타입을 정의하고 있는데요, Operation1과 Operation2 각각의 정의 방식과 차이점을 설명해주세요.

```ts
type Operation1 = (a: number, b: number) => number;

type Operation2 = {
  (a: number, b: number): number;
};
```

💡Q2. 오류가 나는지 O,X로 표시하고, 오류가 나는 경우 이유를 설명해주세요
```ts
let func1: (x: number, y:number) => void;
let func2: (x:number) => console.log(x);

func1 = func2;    //Q2-1. O/X
func2 = fun1;     //Q2-2. O/X

let func3: () => string;
let func4: () => 'Hello, Wave Web !!';

func4 = func3;      //Q2-3. O/X
func3 = func4;      //Q2-4. O/X
```

💡Q3. 오류가 나는지 O,X로 표시하고, 오류가 나는 경우 이유를 설명해주세요
```ts
// 두 개의 오버로드 시그니처를 가진 함수 타입
type Overloadfunc = {
    (x: string): void;
    (x: number): void;
};


let simpleFunc: (x: string | number) => void;

let compatibleFunc: simpleFunc = Overloadfunc;  // Q3. O/X ?
```

💡4. 각 소문제에 대한 답을 작성해주세요
```ts
let paramfunc1: (x: number, y?: number) => void;

let paramfunc2 = (x: number, y: number = 10) => console.log(x + y);

paramfunc1 = paramfunc2;  // 4-1. 오류발생 O/X 
paramfunc1(10);   // 4-2 출력값은? 

```

**Comment by yarimu** [comment]
1. `operation1`은 함수 시그니처를 직접 작성해 함수타입을 정의한 방식이고, `operation2`는 함수 시그니처를 객체 타입의 속성으로 정의한 방식이다.

`operation1`과 달리 `operation2` 는 함수 외에도 추가 속성을 부여할 수 있다. 이러한 경우 함수이자 일반 객체를 의미하는 타입으로 정의되며 이를 하이브리드 타입이라고 부른다.
2. (순서대로)
    1. X    
    2. 0    / 매개변수가 더 많은 것은 적은 것에 할당 할 수 없음
    3. 0    / 문자열 리터럴타입에 문자열 타입을 할당할 수 없음
    4. X
3. 0       / 매개변수에 string이 오는 함수의 경우, 매개변수에 number가 오는 함수만 정의되어있으며, 매개변수에 `string | number` 유니온 타입이 오는 함수 타입과는 호환되지도 않음.
4. (순서대로)
    1. X
    2. 20

**Comment by gonn-i** [comment]
A1: 

`Operation 1 `: 함수 타입을 화살표 함수로 표현한 형태
`Operation 2 `: 객체 타입 내에서 시그니처 타입으로 정의된 함수 타입 

`Operation 1`  의 경우 단일 함수 타입을 간단하게 정의할때 사용되며, 
`Operation 2 `의 경우 여러개의 복합 객체 타입이나 여러 개의 함수 시그니처를 담기 위해 사용한다는 차이가 있다.

```ts
// `Operation 2 ` 의 여러 함수 시그니처를 담는 경우 (오버로딩 만들때!) 
interface NumberParser {
  (input: string): number; 
  (input: number): number; 
}
```

A2 
```ts
// 매개변수 타입이 호환되는 지의 여부를 묻는 문제! (특히, 갯수가 다른 경우!) 
let func1: (x: number, y:number) => void;
let func2: (x:number) => console.log(x);

func1 = func2;    //Q2-1. 오류 ❌
func2 = fun1;     //Q2-2.  오류 ⭕️🚨  (매개변수의 개수가 다를때, 매개변수의 개수가 더 많은쪽에만 할당 가능하다! )

// 반환값 타입이 호환되는지를 묻는 문제! 
let func3: () => string;
let func4: () => 'Hello, Wave Web !!';

func4 = func3;      //Q2-3.오류 ⭕️🚨 func4는 Number Literal  이고, func3은 Number이다. 
//  func4는 func3의 슈퍼타입이 아니기 때문에 호환 불가! 
func3 = func4;      //Q2-4. 오류 ❌ 
```

A3 
```ts
// 두 개의 오버로드 시그니처를 가진 함수 타입
type Overloadfunc = {
    (x: string): void;
    (x: number): void;
};

let simpleFunc: (x: string | number) => void;
let compatibleFunc: simpleFunc = Overloadfunc;  // Q3. 오류 ⭕️🚨
```

 `Overloadfunc` 의 경우, `string`과` number` 모두를 받을 수 있도록 정의되어 있는데, 
`simpleFunc` 는 둘(문자열 / 숫자) 중 하나만을 받을 수 있도록 정의되었기에 타입 호환 에러 발생! 

A4 
```ts
let paramfunc1: (x: number, y?: number) => void;
let paramfunc2 = (x: number, y: number = 10) => console.log(x + y);

paramfunc1 = paramfunc2;  // 4-1.  오류 ❌
paramfunc1(10);   // 4-2 출력값은? 20
```
선택적 매개변수 y?: number 와 y: number = 10 는 서로 호환되기 때문에 오류가 발생하지 않는다.

**Comment by gwagjiug** [comment]
```typescript
type Operation1 = (a: number, b: number) => number;

type Operation2 = {
  (a: number, b: number): number;
};
```
1번 방법은 함수 선언 및 구현코드와 타입 선언을 분리할 수 있어서 유용합니다!
2번 방법은 함수의 타입을 별도로 정의하는 방식입니다! 객체 취급 되는 것 맞나요? 프로퍼티도 추가로 정의할 수 있다고 합니다.

---

```typescript
let func1: (x: number, y:number) => void;
let func2: (x:number) => console.log(x);

func1 = func2;    //Q2-1. 오류 X
func2 = fun1;     //Q2-2. 오류 O

let func3: () => string;
let func4: () => 'Hello, Wave Web !!';

func4 = func3;      //Q2-3. O
func3 = func4;      //Q2-4. X
```
매개변수의 개수가 다를 때의 호환 가능성을 묻는 문제 같습니다!

2-2: func2의 매개변수가 func1의 매개변수보다 적기때문에 할당이 불가능합니다.
2-3: func4는 문자열 리터럴 타입이고, func3 는 문자열 타입이기에 할당이 불가능합니다

---

```typescript
// 두 개의 오버로드 시그니처를 가진 함수 타입
type Overloadfunc = {
    (x: string): void;
    (x: number): void;
};


let simpleFunc: (x: string | number) => void;

let compatibleFunc: simpleFunc = Overloadfunc;  // Q3. O/X ?
```

0 입니다 오버로드된 함수는 구체적인 타입으로 분기되기 때문에 단일 시그니처로 처리해야 합니다.

---

```typescript
let paramfunc1: (x: number, y?: number) => void;

let paramfunc2 = (x: number, y: number = 10) => console.log(x + y);

paramfunc1 = paramfunc2;  // 4-1. 오류발생 O/X 
paramfunc1(10);   // 4-2 출력값은? 
```
1. 발생하지 않는다.
2. 20

**Comment by heesunee** [comment]
### 함수 타입 표현식과 호출 시그니쳐의 차이점

A 1: Operation1은 함수 타입 표현식으로, Operation2는 호출 시그니쳐로 정의되어 있습니다. 

함수 타입 표현식의 경우 (a: number , b:number) ⇒ number 과 같은 형식으로 독립적인 함수 타입을 정의합니다. 객체 내부에 포함되지 않으며 함수 자체를 변수나 타입에 할당할 때 사용됩니다.

호출 시그니쳐의 경우 객체 타입 내에서 함수의 시그니처를 정의합니다. 이는 객체 내부의 메서드로서 함수 타입을 정의합니다. 여러 복합 객체 타입이나 여러 함수 시그니처를 담아 (오버로딩) 하나의 함수를 매개변수의 개수나 타입에 따라 다르게 동작하도록 만들 수 있습니다.

### 매개변수의 수가 적거나 많은 경우

A 2-1: X

A 2-2: O, func2는 매개변수가 하나로 설정되어 있습니다.  

### 반환 타입의 호환성

A 2-3: O

A 2-4: X

반환 타입의 경우, 반환 타입이 더 구체적인 타입으로 대체가 가능할 때 호환됩니다.

fun3 = string 타입

fun4 = string literal 타입

fun3이 fun4의 슈퍼타입입니다. 

### 오버로드 호환성

A3: O

simpleFuc는 string 또는 number를 인수로 받아들이는 하나의 시그니처만 존재합니다. 반면 Overloadfunc는 두 개의 오버로드된 시그니처를 가지는 함수 타입이므로 서로 호환되지 않기때문에 할당할 수 없습니다.

### 선택적 매개변수 호환성

A 4-1: X

A 4-2: 20

param1에서 y는 선택적 매개변수 이므로   y는 param2에서 기본값 10이 사용되어 x+y의 값은 20이 됩니다.
