### ISSUE TITLE
[3주차/이예림] 클래스 접근제어자

### ISSUE THREAD

**Issue by yarimu** [SOPT-all/35-STUDY-WEB-PEACANG#14]
### 문제

오류가 발생여부를 O,X로 나타내고 오류를 반환한다면 그 이유를 설명해 주세요!

문제 1️⃣
```javascript
class Employee {
    private name: string;
    public age: number;
    protected position: string;
    
    constructor(name: string, age: number, position: string) {
        this.name = name;
        this.age = age;
        this.position = position;
    }
}

const employee = new Employee("이정환", 27, "developer");
console.log(employee.name);  // 오류? (O / X)
```

문제 2️⃣
```javascript
class Employee {
    constructor(private name: string, protected age: number, public position: string) {}
}

const employee = new Employee("이정환", 27, "developer");
employee.age = 30;  // 오류? (O / X)
```

문제 3️⃣
```javascript
class Employee {
    private name: string;
    constructor(name: string) {
        this.name = name;
    }
}

class Developer extends Employee {
    constructor(name: string, private language: string) {
        super(name);
        console.log(this.name); // 오류? (O / X)
    }
}
```

문제 4️⃣
```javascript
class Employee {
    protected age: number;
    constructor(age: number) {
        this.age = age;
    }
}

class Manager extends Employee {
    constructor(age: number, private department: string) {
        super(age);
    }
    getAge() {
        return this.age; // 오류? (O / X)
    }
}
```

문제 5️⃣
```javascript
class Employee {
    public position: string;
    constructor(position: string) {
        this.position = position;
    }
}

const employee = new Employee("developer");
employee.position = "designer"; // 오류? (O / X)
```

**Comment by gonn-i** [comment]
A1:
오류가 발생한다 ⭕️ ` private` 접근 제어자로 선언된 `name`을 클래스 외부에서 직접 접근할 수 없기 때문이다. 

A2:
오류가 발생한다 ⭕️ ` protected` 접근 제어자로 선언된  `age` 역시 클래스 외부에서 접근할 수 없다. 
다만, 클래스 내부와 파생된 클래스에서만 접근이 가능하다!

A3: 
오류가 발생한다 ⭕️  `private` 접근 제어자로 선언된 `name`을 클래스 외부에서 직접 접근할 수 없다. 다만, 오류를 해결하기 위해 `private` 대신 ` protected`을 사용하면 오류를 정정할 수 있다.

A4: 오류가 발생하지 않는다  ❌
` protected` 접근 제어자로 선언된 `age` 는 파생된 클래스에서 접근 가능하기 때문이다. 

A5: 오류가 발생하지 않는다  ❌
` public` 접근 제어자로 선언된 `position` 는 어디서든지 이 프로퍼티에 접근 가능하기 때문이다.

**Comment by gwagjiug** [comment]
A1 : 에러입니다. 접근 제어자를 `private` 으로 설정하면 크래스 내부에서만 필드에 접근할 수 있습니다.
A2 : 오류가 발생한다. `protected` 접근 제어자로 선언된 `age` 는 클래스 외부에서 접근이 안된다! 하지만 내부와 파생 클래스에서 접근은 가능합니다.
A3: 오류가 발생합니다 마찬가지로 외부에서 접근할 수 없지만 protected를 사용하면 정정할 수 있습니다.
A4 : 오류 없습니다. 
`protected` 접근 제어자는 파생된 클래스에서 접근이 가능합니다.
A5 : 오류 없습니다. 
public은 어디서든지 접근 가능하기 때문입니다.

**Comment by heesunee** [comment]
A1: O

현재 Employee 클래스의  name 필드는 private로 설정되어있습니다. private 접근 제어자는 클래스 내부에서만 접근가능합니다.  `console.log(employee.name)`은 클래스 외부에서 접근하려 하기 때문에 오류가 발생합니다.

A2: O 

age는 protected 접근제어자로 설정이 되어있습니다. protected는 클래스 내부나 파생 클래스 내부에서만 접근이 가능한데 현재 클래스 외부에서 접근하려 하고 있으므로 오류가 발생합니다.

A3: O

name은 private로 클래스 내부에서만 접근이 가능합니다. 문제에서는 Developer 파생 클래스 내부에서 name에 접근하려 하고 있어 오류가 발생합니다.

A4: X

age는 protected 접근제어자로 설정되어있습니다. getAge()는 Employee의 파생클래스인 Manager에서 선언되어있으므로 age에 접근이 가능합니다. 오류가 발생하지 않습니다.

A5: X

오류가 발생하지 않습니다. public 접근제어자는 어디서든지 접근이 가능합니다.

**Comment by yarimu** [comment]
1️⃣ 
- 정답: 0
- 이유:  `name`필드는 Employee클래스의 `private` 접근 제어자이므로, Employee클래스 내부에서만 접근 가능하다.
- 수정: `name`필드의 접근 제어자를 `public`으로 변경

2️⃣
- 정답: 0
- 이유: `age`필드는 Employee객체 내부 또는  Employee객체 파생 클래스에서만 접근 가능하다.
- 수정: `age`필드의 `protected`접근 제어자를 `public`으로 수정

3️⃣
- 정답: 0
- 이유: `name`필드는 `private` 접근 제어자이므로 파생클래스 내부에서 접근할 수 없다.
- 수정: `name`필드의 접근 제어자를 `public` 또는 `protected`로 수정

4️⃣
- 정답: X
- 이유: `age`필드는 `protected`접근 제어자로 파생클래스 내부에서 접근 가능하다.

5️⃣
- 정답: X
- 이유: `position`필드는 `public`접근 제어자이므로 Employee외부에서 접근 가능하다.
