### ISSUE TITLE
[3주차/곽지욱] 함수 타입의 호환성

### ISSUE THREAD

**Issue by gwagjiug** [SOPT-all/35-STUDY-WEB-PEACANG#15]
### 문제

1. 함수 타입의 호환성을 판단하는 기준 2가지가 무엇인지 설명해주세요

2. O/X 를 표시해주세요
```typescript
type A = () => string;
type B = () => 'kim';

let a: A = () => 'hello';
let b: B = () => 'kim';

a = b; // [O/X]
b = a; // [O/X]
```

```typescript
type C = (value: number) => void;
type D = (value: 10) => void;

let c: C = (value) => console.log(value);
let d: D = (value) => console.log(value);

c = d; // [O/X]
d = c; // [O/X]
```

**Comment by gonn-i** [comment]
A1: 
>함수 타입 호환성 판단 기준 
1️⃣ 두 함수의 **반환값 타입이 호환**되는가
2️⃣ 두 함수의 **매개변수의 타입이 호환**되는가

A2: 
```ts
type A = () => string;
type B = () => 'kim';

let a: A = () => 'hello';
let b: B = () => 'kim';

a = b; // 오류 발생 X // A 반환값 타입  ==  B 반환값 타입의 슈퍼타입일때   호환가능
b = a; // 오류 발생 O 
````

```ts
type C = (value: number) => void;
type D = (value: 10) => void;

let c: C = (value) => console.log(value);
let d: D = (value) => console.log(value);

c = d; // 오류 발생 O
d = c; // 오류 발생  X // C 매개변수의 타입 ==  D 매개변수 타입의 서브 타입일 때에 호환
```

**Comment by heesunee** [comment]
A1:
두 함수의 매개변수의 타입이 호환되는지, 반환 값의 타입이 호환되는지 판단해야 합니다.

A2:
```ts
type A = () => string;
type B = () => 'kim';

let a: A = () => 'hello';
let b: B = () => 'kim';

a = b; // X
b = a; // O
```

첫 번째의 경우 오류가 일어나지 않습니다. 현재 두 함수의 매개변수가 없기 때문의 반환 값의 타입이 호환되는지 확인해야 하는데, A의 경우 String, B의 경우는 kim 이라는 String literal로 설정되어있습니다. 이 경우 string이 string literal의 슈퍼타입입니다. 따라서 a에 b를 할당하는 것은 가능하지만 b에 a를 할당하는 것은 불가능합니다.

```ts
type C = (value: number) => void;
type D = (value: 10) => void;

let c: C = (value) => console.log(value);
let d: D = (value) => console.log(value);

c = d; // O
d = c; // X
```

C는 숫자 전체(number)를 매개변수로 받을 수 있는 함수 타입입니다.
D는 특정 숫자 리터럴 값 10만을 매개변수로 받는 함수 타입입니다.
따라서 c에는 더 여러가지의 수를 받아야하는데, d를 할당할 경우 더 좁은 값으로 제한해버리게 됩니다. 매개 변수 타입은 서브타입을 요구하는 쪽으로만 할당이 가능하기 때문에 c=d를 할 경우 오류가 발생합니다.

**Comment by yarimu** [comment]
1. 

> 1️⃣ 반환값의 타입이 호환되는가?
2️⃣ 매개변수의 타입이 호환되는가?
> 
2. 호환가능, 호환 불가능 (X,0)
3. 호환불가능, 호환 가능(0,X)

**Comment by gwagjiug** [comment]
## 정답 및 풀이

**정답 및 해설**: 할당 가능 여부

- `a = b; // O`
- `b = a; // X`

A의 반환값 타입은 `string` `B` 의 반환값 타입은 `kim` 

타입 스크립트에서 함수의 반환 타입은 `공변성` 을 따르므로, 반환 타입이 더 구체적인 (10) B 반환타입이 더 포괄적인 (number) A 에 할당하는 것은 가능하다.

---

**할당 가능 여부**

X , O

c 는 모든 숫자를 매개변수로 받을 수 있는 함수여야 함. 하지만 d 는 10이라는 구체적인 값만 매개변수로 받을 수 있기 때문에 안전하지 않은 할당 으로 간주 됨

## 공변성이란?

- 공변성이란?
    
    함수의 반환 타입에 있어서 공변성은 함수의 반환 타입이 더 구체적인 것으로 더 일반적인 것으로 대체될 수 있다는 원칙
    
    더 쉽게 얘기하면 **반환값이 더 구체적일수록, 그것을 더 일반적인 타입에 할당할 수 있다는 의미**
