### ISSUE TITLE
[4주차/곽지욱] 제네릭은 무조건 좋을까?

### ISSUE THREAD

**Issue by gwagjiug** [SOPT-all/35-STUDY-WEB-PEACANG#17]
### 문제

안녕하세요 이 문제가 `찐` **4주차 문제입니다.** 

제네릭에 대해 공부하다 보니깐 장점들만 눈에들어와서 `주관식` 문제를 내보려고합니다.

제네릭은 함수의 타입, 인터페이스, 클래스 심지어는 Promise 등등 다양한 곳에 사용이 가능합니다.

타입을 미리 특정하지 않고, 호출 시점에 지정할 수 있기 때문에 `그렇다면 무조건 제네릭을 사용하는 것이 가장 좋은 방법인가?` 

라는 물음이 생겼습니다.  하지만 분명 장단점이 있겠죠? 

1. 제네릭의 장단점에 대해서 적어주세요
2. 제네릭은 어떠한 `상황` 에서 사용하는 것이 좋을지 적어주세요

**Comment by gonn-i** [comment]
💭A1: 제네릭의 장점 
포괄적으로 모든 타입 값을 담아낼 수 있다는 장점을 가지고 있습니다. 제네릭 타입은 함수 호출시에 결정되기 때문입니다. 마치 변수처럼 사용할 수 있기에 유연하게 타입을 구성할 수 있다는 장점을 가지고 있습니다. 

💭A2: 
배열타입의 인수를 받을때, 특히 아직 어떤 변수가 할당될지 확실하게 정해지지 않는 경우 유용하다고 생각합니다. 
호출시 인수가 할당되었을 때 타입이 결정되는 제네릭의 특성상, 사용 예제를 살펴보면 호출에 따라 타입이 유연하게 적용될 수 있음을 확인 가능합니다.
```ts 
function returnFirstValue<T>(data: T[]) {
  return data[0];
}

let num = returnFirstValue([0, 1, 2]); // T는 Number 타입으로 추론

let str = returnFirstValue([1, "hello", "mynameis"]); //T는 String | Number 타입으로 추론

```

**Comment by yarimu** [comment]
1️⃣ 제네릭의 장단점
제네릭은 여러 타입을 사용하는 함수 설계에 유용해 재사용성을 제공하는 것입니다. 하지만, 여러 타입을 지원하는 과정에서 다중 제네릭 사용시 가독성이  떨어지며 코드 복잡성을 야기할 수 있습니다.

2️⃣ 제네릭 활용
다양한 타입을 사용하지만, 동일한 로직을 적용하는 경우(API 응답 데이터 처리)

**Comment by heesunee** [comment]
A1: 제네릭은 타입을 고정하지 않고 호출 시점에 타입을 전달할 수 있다는 점이 가장 큰 장점인 것 같습니다. 그로 인해 함수나 클래스 등을 선언할 때 타입을 고정하지 않고, 사용할 때 명시에 더 유연하게 사용할 뿐만 아니라 안정성까지 올라갑니다. 단점을 많이 생각해봤는데요... 우선 초보자에게 많이 어려울 수 있다고 생각합니다. 다소 번거롭더라도 직관적으로 타입을 명시하는 것이 더 좋을 것 같습니다. 

A2: 여러 타입에 대해 동일 로직을 적용할 때 제네릭을 사용하면 코드의 재사용성이 올라갈 수있습니다. 또 특정 조건을 만족하는 타입만 허용하도록 타입 제약이 필요한 경우에도 유용하다고 생각합니다

**Comment by thisishwarang** [comment]
1. 제네릭은 타입을 선언시에 정하는것이 아닌 호출시점에서 정해지도록 유연하게 타입을 정의할 수 있다. 타입 변수라는 이름을 가진것처럼 제네릭을 하나의 변수로 생각하여 타입을 유연하게 만드는것이 가장 큰 장점이라고 생각한다. 반면 단점으로는 코드의 가독성이 떨어지거나 복잡해질 수 있다.

2. 같은 로직을 통해 매개변수와 결과값을 정의하지만, 타입이 유동적일때 적극 활용할 수 있다.

**Comment by gwagjiug** [comment]
장점 : 호출 시점에 타입을 지정할 수 있으므로 재사용성이 높아지고, 그만큼 유연한 코드 작성이 가능해집니다. 뿐만 아니라 input output 의 일관성이 보장되기 때문에 `타입 안정성` 또한 보장됩니다.

단점으로는 불필요한 복잡성이 증가할 가능성이있고 오히려 복잡한 타입 체계를 야기할 수 있습니다.

A2 : 동일한 로직을 여러 타입에 적용할 때 적합합니다. 예를 들면 컬렉션 작업 : (Array, Map, Set) 등 로직은 동일하지만 여러 타입에 적용될 때는 제네릭을 사용하는 것이 안전하다.

그리고 함수의 인풋과 아웃풋의 타입이 같은 경우 (반환 타입의 타입이 같아야 하는 경우! 제네릭 사용이 좋습니다)
