### ISSUE TITLE
[4주차/ 김고은] 타입 조작  

### ISSUE THREAD

**Issue by gonn-i** [SOPT-all/35-STUDY-WEB-PEACANG#18]
### 문제

💭
Q1  다음의 코드가 비효율적인 이유를 적어주세요 :) 
Q2  더 나은 코드를 위해 타입 조작 연산자를 사용하여 코드를 수정해주세요 

```ts
interface Sopt {
  collaboration: string;
  appjam: string;
  soptkatonId: number; 
}

function weAreWebby(sopt: Sopt, key: "collaboration" | "appjam" | "soptkatonId") {
  return sopt[key];
}

const sopt: Sopt = {
  collaboration: '롯데시네마',
  appjam: '선약',
  soptkatonId: 3, 
};

```

**Comment by gwagjiug** [comment]
1. key의 타입을 "collaboration" | "appjam" | "soptkatonId" 로 정의하면 Sopt 타입에 새로운 프로퍼티가 추가되거나 삭제되거나 할 때 마다 해당 부분 코드도 계속 수정될 때 마다 이 타입도 계속 바꿔줘야 하기 때문에 유지보수 측면에서 비효율적입니다.


```typescript
function weAreWebby (sopt : Sopt, key : keyof Sopt) {
return sopt[key];
}
```

**Comment by yarimu** [comment]
1️⃣ 비효율적인 이유
매개변수 key의 타입을 `"collaboration" | "appjam" | "soptkatonId"`명시적으로 작성해 새로운 속성이 추가되면 타입 정의를 매번 수정해야 한다는 점에서 유지보수성이 떨어진다. 

2️⃣ 수정한 코드
```javascript
function weAreWebby(sopt: Sopt, key: keyof Sopt) {
  return sopt[key];
}
```

**Comment by heesunee** [comment]
A1: Sopt 인터페이스에 새로운 프로퍼티가 추가되거나 수정될 때마다 weAreWebby 함수의 타입도 매번 수정해줘야 하기 때문에 비효율적입니다.
A2:
```ts
interface Sopt {
  collaboration: string;
  appjam: string;
  soptkatonId: number; 
}

function weAreWebby(sopt: Sopt, key: keyof Sopt) {
  return sopt[key];
}


```

**Comment by thisishwarang** [comment]
1. Sopt 라는 인터페이스에 새로운 프로퍼티가 추가될 때마다 "collaboration" | "appjam" | "soptkatonId" | ... 이 뒤로 프로퍼티를 추가해줘야 하는 불편함이 있다.

2. 
```ts
function weAreWebby(sopt: Sopt, key: keyof Sopt) {
  return sopt[key];
}
```

**Comment by gonn-i** [comment]
A1: 

key 파라미터는 `"collaboration" | "appjam" | "soptkatonId"`로 고정되어있습니다. 

인터페이스에 새로운 프로퍼티가 추가할때마다, 새로운 키를 다시 추가해줘야 하기 때문에 유지보수 면에서 좋지 못하고, 실수로 누락할 가능성도 존재하기 때문에 비효율적입니다.

만약 프로퍼티를 다음과 같이 추가했다면 어떨까요? 

```tsx

interface Sopt {
  collaboration: string;
  appjam: string;
  appjam2: string; // 추가
  appjam3: string; // 추가 
  soptkatonId: number; 
  soptkatonId2: number;  // 추가 
  soptkatonId3: number;  // 추가 
}

function weAreWebby(sopt: Sopt, key: "collaboration" | "appjam" | "soptkatonId" | //....추가된 프로퍼티를 반영해줘야 한다!) {
  return sopt[key];
}
```

A2: 

 `typeof`연산자를 이용하면  프로퍼티의 모든 `key`들을 `String Literal Union` 타입으로 추출할 수 있기 때문에, 더 나은 코드가 됩니다!
