### ISSUE TITLE
[1주차/ 김고은]  타입스크립트의 동작 원리

### ISSUE THREAD

**Issue by gonn-i** [SOPT-all/35-STUDY-WEB-PEACANG#2]
### 문제

❓ : 타입스크립트의 동작 원리를 자바스크립트 동작 원리와 비교하여 설명하세요.  (프로그래밍 언어를 바이트 코드로 변환하는 과정을 서술)

**Comment by gwagjiug** [comment]
자바 스크립트는 우리가 작성한 코드를 `컴파일` 하면서 바이트 코드라는 형식으로 변환하는데,

이 과정에서 우선 코드를 AST(추상 문법 트리) 라는 형태로 먼저 변환합니다.  간단하게 얘기하면 코드의 공백이나 주석 탭 등의 코드 실행에 `관계 없는` 요소들을 제거하고,

트리형태의 자료구조에 코드를 쪼개서 저장해놓습니다. 그리고 이 쪼개진 코드를 `컴파일러` 가 바이트 코드로 변환합니다.

타입스크립트도 기초적인 전개는 비슷하지만 AST를 바이트코드로 전환하기 전 코드 상에 타입 오류가 없는지 `검사` 하는 단계가 추가됩니다.

그리고 실패한다면 컴파일을 중단 시키고 성공한다면 `ts` 코드를 `js` 코드로 변환하고 종료합니다.

**Comment by yarimu** [comment]
TS와 JS 동작 원리의 가장 큰 차이점은 '타입검사'에 있다.

TS는 컴파일러가 코드를 처리할 수 있도록 AST를 생성하여 컴파일러를 통해 JS로 변환된 후 실행된다. 
이 과정에서 타입검사에 실패할 경우, 즉시 컴파일이 종료되며
반대로 검사에 성공할 경우, 타입과 관련된 코드들은 컴파일 결과 사라지게 되어 런타임에서는 JS처럼 동작한다. 

TS 코드가 JS로 변환된 이후 다시한번 추상 구문 트리를 생성하고, 컴파일 과정을 통해 AST를 바이트 코드로 변환해 최적화를 진행해 최종적으로 실제 코드가 수행된다.

**Comment by thisishwarang** [comment]
자바스크립트를 포함한 대부분의 프로그래밍 언어들은 컴파일러에 의해 바이트코드, 즉 컴퓨터가 알아듣는 기계어로 변환됩니다.

하지만 타입스크립트는 다른 언어들과는 달리 두번의 과정을 거치는데 먼저 ts로 작성된 코드를 AST 형태로 변환하고 이때 타입 검사를 실시합니다. 타입 검사에 실패했다면 그대로 컴파일이 종료되고, 타입 검사를 통화했다면 js코드로 먼저 변환됩니다.
이후 다시한번 js로 작성된 코드를 AST 형태로 변환하고 컴파일러에 의해 바이트 코드로 변환되어 실행되게 됩니다.

**Comment by heesunee** [comment]
일반적으로 자바스크립트를 포함한 대다수의 언어에서는 `코드` →` AST(추상 문법 트리)` → `바이트 코드`의 변환 과정을 거쳐 컴파일됩니다. 

타입스크립트는

1. `코드 → AST 변환`
2. `타입검사`: AST 생성 후, 코드에 타입 오류가 없는지 검사합니다. 오류가 발견되면 컴파일이 중단되며, 오류가 없다면 다음 단계로 진행합니다.
3. `AST → JavaScript 변환`: 타입 오류가 없을 경우, AST를 자바스크립트 코드로 변환합니다. 이 때 타입 관련 코드나 문법은 제거됩니다
4. `JavaScript 컴파일`: 변환된 코드는 일반 JavaScript와 마찬가지로 바이트 코드로 컴파일 됩니다.

이 과정을 통해, TypeScript는 **안전한 JavaScript 코드**로 변환되어 타입 오류 발생 가능성을 줄이고, 실행 중 발생할 수 있는 오류를 예방할 수 있습니다.

**Comment by gonn-i** [comment]
JS : `프로그래밍언어` -> `AST (추상 문법 트리)` -> `바이트 코드`
TS : `프로그래밍언어` -> `AST (추상 문법 트리)` -> (타입 오류 검사: 오류 없어야 다음으로)
-> `JS로 변환` -> `바이트 코드`


자바스크립트는 프로그래밍 언어에서 컴파일 과정을 통해 -> AST를 거쳐 기계어인 바이트 코드로 바로 변환됩니다.
반면에, 타입스크립트는 자바스크립트와 달리, 타입 오류가 있는지를 체크하고 바이트 코드로 변환합니다. 그렇기 때문에, 타입으로 인한 논리적인 오류를 방지할 수 있습니다.
