### ISSUE TITLE
[5주차 / 김고은] 타입 효율화를 위한 타입 설계 

### ISSUE THREAD

**Issue by gonn-i** [SOPT-all/35-STUDY-WEB-PEACANG#23]
### 문제

💭 이번 주제에 범위는 적지 않겠습니다
(범위를 정해버리면 답이 정해지는 느낌이라! 자유롭게 생각해주세요) 

> 여러분은 네이버 지식인을 모방한 게시글 작성과 수정 기능을 구현하려고 합니다!! 
아래의 타입을 보고, 데이터를 효율적으로 관리하기 위해 **타입 분리**와 **유틸리티 타입**을 활용해보세요 🎯 

```ts
// 게시글 구조에 대한 타입 
type Post = {
  title: string; // 제목
  content: string; // 세부 내용
  userName: string; // 작성자 이름
  userState: string; // 작성자 칭호 (바람신, 태양신 .. 등 편의상 string으로 두겠습니다) 
  userAnswerCount: number; // 유저의 답변수 
  wordCount: number; // 글자수
  likes: number; // 추천수
  date: Date;  // 작성날짜
};

// 수정 가능한 필드에 대한 타입 
type EditPost =  {
  title: string; // 제목
  content: string; // 세부 내용
};
```

**Comment by yarimu** [comment]
우선, 의도하신바가 제 풀이와 맞을지 걱정은 되지만,, 풀어보겠습니다!?
중복되는 프로퍼티는 따로 분리하고, 프로퍼티의 속성에 따라 타입을 나누고, 유틸리티 타입 중 `Pick`을 사용해 보았습니다.
`type EditPost = Pick<BasePost, "title" | "content">`
`type EditPost = BasePost`와 같아 보일 수 있지만, 의도적으로 "title", "content"만 포함해 추후 EditPost에 다른 프로퍼티가 추가 되더라도, EditPost에 영향을 주지 않도록 Pick을 사용했습니당!

```javascript
type BasePost = {
  title: string; // 제목
  content: string; // 세부 내용
}

type User = {
  userName: string; // 작성자 이름
  userState: string; // 작성자 칭호 (바람신, 태양신 .. 등 편의상 string으로 두겠습니다) 
  userAnswerCount: number; // 유저의 답변수 
}

type PostData = {
  wordCount: number; // 글자수
  likes: number; // 추천수
  date: Date;  // 작성날짜
}


type Post = BasePost & User & PostData

type EditPost = Pick<BasePost, "title" | "content">;
```

**Comment by thisishwarang** [comment]
```ts
type Post = {
  title: string; // 제목
  content: string; // 세부 내용
  userName: string; // 작성자 이름
  userState: string; // 작성자 칭호 (바람신, 태양신 .. 등 편의상 string으로 두겠습니다) 
  userAnswerCount: number; // 유저의 답변수 
  wordCount: number; // 글자수
  likes: number; // 추천수
  date: Date;  // 작성날짜
};

// 수정 가능한 필드에 대한 타입
type EditPost = Pick<Post, 'title' | 'content'>;
```

문제 풀기 전에 예림님 답변을 어쩌다보니(?) 읽게 되었는데 예림님처럼 프로퍼티들을 관심사분리를 통해 3개로 나누는것도 좋은 방식이라고 생각했습니다. 그런데 만약 EditPost 타입에 새로운 프로퍼티가 아닌 User 혹은 PostData 타입에 있는 프로퍼티를 추가해줘야하는 상황이라면 EditPost 타입이 더욱 복잡해질수도 있다 생각하여 간단하게 Pick 유틸리티 타입만을 사용하여 문제를 풀어보았습니다.

**Comment by heesunee** [comment]
위에 좋은 답변들이 많아서 ! 저는 게시글 관련된 속성을 Post에, 작성자 관련된 속성은 User로 나누어서 관리해보았습니다.

```ts
// 작성자 관련 정보 타입
type User = {
  userName: string;  // 작성자 이름
  userState: string;  // 작성자 칭호 (예: 바람신, 태양신)
  userAnswerCount: number;  // 유저의 답변수
};

// 게식글 관련 정보 타입
type Post = {
  title: string;  // 제목
  content: string;  // 세부 내용
  wordCount: number;  // 글자수
  likes: number;  // 추천수
  date: Date;  // 작성날짜
  user: User;  // 작성자 정보 (User 타입 사용)
};


type EditPost = Pick<Post, 'title' | 'content'>;

```

Post 타입 내에서 User를 받도록 했습니다. Post 타입에 댓글이나 관련 정보가 추가될때 User 타입은 변경하지 않아도 될 것이라 생각했습니다.

이 외에 추가적으로 생각해보자면 .. 게시글 관련 정보 타입에 `카테고리` 등과 같은 추가 정보가 있고, 수정 가능한 정보가 훨씬 많다면 pick보다는 omit을 활용해 수정할 수 없는 필드를 제외한 타입을 생성하는 방법도 효과적일 것 같습니다.

```ts
// 수정할 수 없는 필드를 제외한 타입 생성: title, content, category만 수정 가능
type EditPost = Omit<Post,  'user' | 'date' | 'wordCount' | 'likes'>;
```

 **(만약 수정할 수 있는 정보가 많고, 삭제할 프로퍼티가 많다면)**

**Comment by gwagjiug** [comment]
문제가 넘 재밌어서 다른 답변들을 다 읽다보니깐 똑같은 답변을 반복할 것 같아서 그냥 느낀점을 말씀드리자면

처음엔 당연히 특정 도메인의 데이터별로 타입을 분리해서 예림님과 유사한 정답이 나왔었는데, 화랑님의 답변도 일리가 있는 주장인 것 같아요 정확하게는 모르지만 

각 수정 가능한 영역별 인터페이스를 생성해서 관리하게 되면 추후에 인터페이스가 계속 늘어날 수도 있고 새로운 필드 추가시에 여러 곳을 수정해야 하기 때문에 유지보수 측면을 고려해서 다른 시각을 제시해주신거 맞나요??

화랑님이 꼭 이 부분에서 추가설명을 해주면 너무 좋을 것 같아요 ㅎㅎ

**Comment by gonn-i** [comment]
```ts
// User 타입 정의
type User = {
  name: string; // 작성자 이름
  state: string; // 사용자 상태 
  answerCount: number; // 유저 답변수 
};

type Post = {
  title: string; // 제목
  content: string; // 세부 내용
  wordCount: number; // 글자수
  likes: number; // 추천수
  date: Date;  // 작성날짜
  author: User; // 작성자의 정보를 담은 author 타입객체 
};

type EditPost = Pick<Post, 'title' | 'content'>;
```
