### ISSUE TITLE
[5주차/곽지욱] 유틸리티 타입

### ISSUE THREAD

**Issue by gwagjiug** [SOPT-all/35-STUDY-WEB-PEACANG#24]
### 문제

* Partial<T>의 맵드 타입 구현 방식을 설명하고, 각 부분의 역할을 자세히 설명해주세요
* [key in keyof T]? 문법의 의미를 정확히 설명해주세요

**Comment by gonn-i** [comment]
`Partial 유틸리티` === 특정 객체 타입의 모든 프로퍼티를 **선택적 프로퍼티로 반환**할 수 있도록 하는 도구 
구현 방식은 아래와 같습니다!!!

```ts
type Partial<T> = {
  [key in keyof T]?: T[key];
};
```

설명 부분을 좀 쌓아가면서 해볼게요..!  두 질문 한번에 대답해보도록 하겠습니당

> ` Partial<T>` 는 제네릭 타입으로, T 를 호출시 동적으로 받아서 사용하기 때문에, T는 어떤 객체 타입이 될 수 있음!

> `keyof T`는 T에 대한 모든 키값을 가져오기 때문에,
> `key in keyof T` 에서 제일 앞에 `key`는 가져온 T 타입의 키 하나하나를 의미합니다! 

> ` [key in keyof T]?` 여기에 물음표가 붙었다는 건, 해당 부분이 선택적 속성으로 자리잡아 있어도 없어도 괜찮음을 의미해요!  그래서 합쳐보면!

 ` [key in keyof T]?: T[key]`  모든 속성들을 선택적 속성으로 만들어주는 타입으로, 제일 뒤에 ` T[key]` 라고 적어주어 주어진 타입은 그대로 유지하되 부분적으로 사용할 수 있게끔 나타낸 표현입니다!

**Comment by yarimu** [comment]
1. Partial은 TS 유티리티 타입 중 하나로, 특정 객체 타입 T의 모든 프로퍼티를 선택적 프로퍼티로 바꿔주는 타입이다.
    
    Partial은 제네릭 타입이며 T라는 타입 매개변수를 받는다.
    
2. `[key in keyof T]? : T[key];`
    
    `keyof T` 는 T의 모든 키를 유니온 타입으로 추출한다.
    
    `?` 는 해당 키를 선택적으로 만든다.
    
    `T[key]` 는 key에 해당하는 타입을 참조한다.
    
    `in` : 맵드 타입에서 특정 키 집합을 순회한다.
    
    따라서 T의 모든 키를 선택적으로 포함하여, 각 키의 타입은 T에서 가져오는 맵드 타입을 정의한다.

**Comment by thisishwarang** [comment]
1. 
```ts
type Partial<T> = {
  [key in keyof T]?: T[key];
};
```

2. keyof T는 제네릭 타입 변수인 T 객체에서 모든 key 값을 가져옵니다.
key in keyof T를 함으로써 T 객체에서 가져온 모든 key들을 순회하여 가져옵니다.
이때 ? 연산자를 붙여 모든 key들을 옵셔널로 만들어주었습니다.

**Comment by heesunee** [comment]
1. Partial<T> 타입은 타입변수 T로 전달할 객체 타입의 모든 프로퍼티를 다 선택적 프로퍼티로 변환합니다.
타입변수 T를 사용하는 제네릭 타입입니다.

```ts
type Partial<T> = {
  [key in keyof T]?: T[key];
};
```
2.
(1) `type Partial<T> `: Partial이라는 이름의 타입을 정의합니다. 이때 Partial은 제네릭을사용하여 타입 변수 T를 매개변수로 받습니다.
(2)` [key in keyof T]?` : 맵드 타입으로 T의 각 속성을 맵처럼 순회하면서 처리합니다. key는 T의 각 속성 이름이며 keyof T는 T 타입의 모든 키를 가져옵니다. ? 물음표는 선택적 속성입니다.
(3)` T[key]`: T 타입의 특정 속성의 값의 타입을 가져옵니다.

즉,
Partial<T>는 T 타입의 모든 속성을 선택적으로 만드는 타입입니다. 예를 들어, T = { a: string, b: number }라면 Partial<T>는 { a?: string, b?: number }

Partial은 객체 업데이트나 초기화 처럼 모든 필드를 선택적으로 만들어야 할 때 유용합니다

**Comment by gwagjiug** [comment]
```typescript
type Partial<T> = {
  [key in keyof T]?: T[key];
};
```

1. keyof T : 제네릭 타입 T의 모든 속성을 유니온 타입으로 추출함 

```typescript
interface Post {
  title: string;
  tags: string[];
  content: string;
}

```

위 코드로 예르르 들자면 keyof Post는 "title" | "tags" | "content" 타입이 됩니다.

`key in keyof T` 는 T 타입의 모든 키를 순회하면서 새로운 타입을 만드는 것이고 

`?: T[key]` 는 각 키의 타입을 선택적 프로퍼티로 만드는 것이다. 반대로 T[key] 는 해당 키의 원래 타입을 그대로 유지하겠죠?
