### ISSUE TITLE
[5주차/임화랑] 유틸리티 타입 & 자유주제

### ISSUE THREAD

**Issue by thisishwarang** [SOPT-all/35-STUDY-WEB-PEACANG#25]
### 문제

1. 
```ts
interface Post {
  title: string;
  tags: string[];
  content: string;
  thumbnailURL?: string;
}

const noTitlePost: Post = {
tags: ['a', 'b'],
content: "",
thumbnailURL: "https://asef.asef",
}
```
위 코드에서 noTitlePost에 에러가 발생하고 있습니다. 유틸리티 타입을 사용하여 에러를 해결해주세요.

2. 합동세미나, 앱잼 등 다양한 팀 프로젝트를 진행하면서 서버에 api를 요청하고, 응답값을 받아 이 응답값으로 어떤 로직을 처리해야하는 코드 많이 짜보셨을것 같습니다. 
```ts
type HostIntroGetResponse = { 예시 타입 }

const getHostInfo = async (hostId: number): Promise<HostIntroGetResponse | null> => {
  try {
    const response = await get<ApiResponseType<HostIntroGetResponse>>(`URL~~~`);
    return response.data.data;
  } catch (error) {
    console.error('error 발생!');
    return null;
  }
};
```
위와 같은 코드에서 반환값의 타입으로는 HostIntroGetResponse 혹은 null 이라는 타입을 지정해주고 있네요.
get요청 할때도 get요청을 통해 받는 response의 타입을 지정해줘야 할텐데 `ApiResponseType` 이라는 타입은 어떻게 정의해야 할까요??

제네릭을 활용해서 ApiResponseType을 만들어주세요.

<details>
<summary>참고!</summary>
<div markdown="1">
 response의 응답값에는 status코드, message, data 객체가 있을것 같습니다.
</div>
</details>

**Comment by heesunee** [comment]
1. 1번문제의 경우 게시글의 임시저장 역할일 때라고 생각됩니다. 모든 필드가 들어가있지 않아도 저장이 이루어져야합니다. 현재 코드에서 Post 인터페이스에서는 title 속성이 필수로 요구되는데, noTitlePost에는 title 속성이 없어서 오류가 발생합니다. 이때는 Partial 유틸리티 타입을 사용할 수 있습니다.

```ts
interface Post {
  title: string;
  tags: string[];
  content: string;
  thumbnailURL?: string;
}

const noTitlePost: Partial<Post> = {
  tags: ['a', 'b'],
  content: "",
  thumbnailURL: "https://asef.asef",
};

```

Partial은 모든 필드를 선택적 요소로 만들어줍니다.

2. response 객체는 status(number), messeage(string), data 세가지 속성을 받습니다. data를 제네릭 타입으로 정의하면 실제 반환되는 데이터 타입을 유연하게 받을 수 있습니다.

```ts
type ApiResponseType<T> = {
  status: number;  
  message: string; 
  data: T;       
};

```
여기서 T는 get 요청을 통해 반환되는 실제 데이터 타입이 됩니다. 문제에서 data는 HostIntroGetResponse 타입이 될 것이기 때문에 response.data.data는 HostIntroGetResponse 타입을 갖습니다.

**Comment by gonn-i** [comment]
A1 
Post의 타입을 가져다가 쓰는 과정에서, 일부를 누락했기 때문에 기대했던 값이 존재하지 않아 오류가 나는 상황인데요! 따라서, 특정 객체 타입의 모든 프로퍼티를 선택적 프로퍼티로 변환할 수 있는 Partial 유틸리티 타입을 사용하면 됩니다! 

```ts
interface Post {
  title: string;
  tags: string[];
  content: string;
  thumbnailURL?: string;
}

const noTitlePost: Partial<Post> = {
tags: ['a', 'b'],
content: "",
thumbnailURL: "https://asef.asef",
}
```

A2.
```ts
type ApiResponseType<T> = {
  success: boolean; 
  message: string; 
  data: T;       
};
```

**Comment by gwagjiug** [comment]
1. 희선님 말씀대로 Partial<T> 를 사용해서 모든 속성을 선택적으로 만들 수 있을 것 같아요 다른 방법도 있나요?


2.
```typescript
type ApiResponseType<T> = {
  status: number; 
  message: string; 
  data: T;       
};
```
