### ISSUE TITLE
[1주차/곽지욱] 자바스크립트의 동적 타입 시스템이 가진 주요 단점은?

### ISSUE THREAD

**Issue by gwagjiug** [SOPT-all/35-STUDY-WEB-PEACANG#3]
### 문제

자바스크립트의 동적 타입 시스템이 가진 주요 단점은 무엇인가요?

그리고 추가적으로 타입스크립트는 어떠한 방식으로 해당 단점을 보완하였나요??

**Comment by yarimu** [comment]
자바스크립트의 동적 타입은 자유롭고 유연하지만, 코드의 타입 오류를 미리 검사할 수 없어서 예기치 못한 오류를 유발 가능성이 크다. 이러한 안전성의 한계를 극복한 것이 타입스크립트이다.
타입스크립트는 정적 타입 시스템을 도입해 변수와 함수의 타입을 코드 작성 단계에서 미리 검사할 수 있게 하여 실행 전 오류를 줄인다. 동시에 선택적 타입 지정 기능을 제공해 모든 변수에 타입을 명시할 필요가 없도록 하여 정적 타입 시스템의 번거로움도 완화하였다.

**Comment by gonn-i** [comment]
논리적인 오류가 발생할 위험이 큽니다. 또한, 변수의 타입이 코드 실행 중에 변경될 수 있어서 안정성이 낮다는 점이 단점입니다.
반면, 타입스크립트의 경우 코드 작성 시 타입을 명시하고 또, 컴파일 단계에서 타입 오류를 검사하기 때문에 안정성을 높였습니다.

**Comment by thisishwarang** [comment]
동적 타입 시스템은 코드를 실행하며 유동적으로 변수의 타입을 결정하기 때문에 코드의 타입 오류를 런타임 전에 미리 검사할 수 없다는 단점이 있습니다. 따라서 예상치 못한 오류가 발생할 수 있고, 이를 런타임에 발견하여 예상치 못한 프로그램 종료로 이어질 수 있습니다.

반면 타입스크립트는 java와 같은 정적 타입 시스템과 js의 동적 타입 시스템의 장점을 합친 점진적 타입 시스템을 채택하여 실행 전에 타입 검사를 통해 타입 안정성을 확보하고, 추후 자동으로 변수의 타입을 추론하여 안정성을 보장합니다.

**Comment by heesunee** [comment]
JavaScript는 동적 타입 시스템을 사용하는 언어이기 때문에 코드의 실행 시점에서 유**동적으로 변수의 타입**이 결정됩니다. 이로 인해 다양한 타입의 유연성을 가질 수 있지만, 특정 타입의 변수에 해당 타입에서 사용할 수 없는 값이 들어가면 `타입 에러`가 발생합니다. 

하지만 TypeScript는 정적 타입 시스템의 장점을 도입하여, 코드 실행 전에 변수의 **타입을 결정**하고 **타입 오류 여부**를 검사합니다. 따라서 코드 실행 전 오류를 발견해 안정성을 확보할 수 있습니다. 뿐만 아니라 타입 추론 기능을 제공하여 모든 변수에 일일히 타입을 명시하지 않더라도 **초기 값에 따라 자동으로 추론**합니다.

따라서 TypeScript는` 타입의 안정성` 뿐만 아니라 `동적 타입 시스템의 유연성`을 동시에 제공합니다.

**Comment by gwagjiug** [comment]
### 정답

자바스크립트의 동적 타입 시스템이 가진 주요 단점은 코드의 타입 오류를 런타임 전에 미리 검사할 수 없다는 점입니다. 타입 검사 없이 코드를 `실행` 하기 때문입니다. 

 타입스크립트는 `C` `Java` 와 같은 정적 타입 시스템과 `JavaScript` 의 동적 타입 시스템의 장점을 합친 점진적 타입 시스템을 채택하여 실행 전에 타입 검사를 통해 타입 안정성을 확보하고, 만약 타입을 정의하지 않았더라도 초기에 입력된 값을 참고하여 자동으로 타입을 지정합니다

**Comment by gwagjiug** [comment]
정답
자바스크립트의 동적 타입 시스템이 가진 주요 단점은 코드의 타입 오류를 런타임 전에 미리 검사할 수 없다는 점입니다. 타입 검사 없이 코드를 실행 하기 때문입니다.

타입스크립트는 C Java 와 같은 정적 타입 시스템과 JavaScript 의 동적 타입 시스템의 장점을 합친 점진적 타입 시스템을 채택하여 실행 전에 타입 검사를 통해 타입 안정성을 확보하고, 만약 타입을 정의하지 않았더라도 초기에 입력된 값을 참고하여 자동으로 타입을 지정합니다
