### ISSUE TITLE
[1주차/박희선]  객체 타입과 프로퍼티 접근 오류

### ISSUE THREAD

**Issue by heesunee** [SOPT-all/35-STUDY-WEB-PEACANG#4]
### 문제

❓다음과 같은 코드에서 `user.id`에 접근할 때 오류가 발생하는 이유는 무엇일까요? 오류 없이 **객체의 프로퍼티에 접근**하려면 어떻게 해야 하나요?

```javaScript
let user: object = {
  id: 1,
  name: "이정환",
};

user.id; // 오류 발생

```

**Comment by gwagjiug** [comment]
타입스크립트의 `object` 타입은 단순 값이 객체임을 표현하는 것 외에는 아무런 정보도 제공하지 않기 때문입니다. 

즉, 이 `object` 타입의 객체는 프로퍼티에 대한 정보를 전혀가지고 있지 않기 때문!

`Q : 오류 없이 객체의 프로퍼티에 접근하려면 어떻게 해야 하나요?`

A : object 가 아닌 객체 리터럴 타입을 이용하면 됩니다.  객체 리터럴 타입으로 선언하여 property에 접근할 수 있는 `타입 정보` 를 제공해주는 것입니다

```typescript
let user: {
  id: number;
  name: string;
} = {
  id: 1,
  name: "이정환",
};

user.id;
```

**Comment by yarimu** [comment]
user객체에 object라고 타입을 정의하는 것은 
> user는 객체 타입!

이라는 정보외에 특정 프로퍼티에 대한 정보를 갖고 있지 않기 때문이다.

구체적인 타입을 지정하기위해 객체 리터럴 타입을 활용할 수 있다.
```javascript
// object
let user: {
	id: number;
	name: string;
} = {
	id: 1,
	name: "이정환",
}
```

**Comment by gonn-i** [comment]
`object` 타입은 **단순 값이 객체임을 표현하는 것외에 정보를 제공**하지 않습니다. 
따라서, 객체의 프로퍼티에 접근하기 위해서는 **객체 리터럴 타입** 으로 타입을 선언해주어야 합니다.

```ts
let dog: {
  name: string;
  color: string;
} = {
  name: "돌돌이",
  color: "brown",
};
```

**Comment by thisishwarang** [comment]
object 타입은 user변수가 단순 객체임을 표현하는 것 이외에 다른 정보를 제공하지 않습니다.
객체의 각 프로퍼티에 접근하기 위해서는 각 프로퍼티 마다 타입을 객체 리터럴 타입으로 지정해줘야 합니다.
```ts
let user: {
  id: number;
  name: string;
} = {
  id: 1,
  name: "이정환",
};
```

**Comment by heesunee** [comment]
**정답**

object 타입은 값 자체가 객체라는 것만 알 수 있을 뿐, 해당 객체가 어떤 프로퍼티를 갖고 또 value는 무슨 타입인지 알 수 없습니다.  따라서 다음과 같이 객체 리터럴을 이용해 객체 타입 선언을 합니다.

```tsx
let user: {
  id: number;
  name: string;
} = {
  id: 1,
  name: "이정환",
};
```

객체에 담길 프로퍼티의 이름과 value의 타입을 직접 작성해주면 타입 오류가 발생하지 않습니다.
