### ISSUE TITLE
[1주차/이예림] 인덱스 시그니처 활용

### ISSUE THREAD

**Issue by yarimu** [SOPT-all/35-STUDY-WEB-PEACANG#5]
### 문제

🍏 아래의 코드는 인덱스 시그니처에서 특정 프로퍼티를 강제하는데 활용한 코드입니다.
오류를 반환하지 않도록 코드를 올바르게 수정하고, 에러가 발생하는 이유에 대해 작성해주세요.

```javascript
type SoptCodes = {
	[key: string]: string;
        Web: number;         // 오류 반환!!
};
```

**Comment by gwagjiug** [comment]
`Q : 에러가 발생하는 이유`
`A : 인덱스 시그니처의 value 타입인 string과 직접 추가한 프로퍼티의 value 타입이 호환되거나 일치해야 하는데 해당 조건을 충족하지 못하기 때문입니다` 
 
```
type SoptCodes = {
	[key: string]: string | number;
        Web: number;
};
```
코드를 이렇게 수정하면 `number` 타입도 가질 수 있게 됩니다.

**Comment by gonn-i** [comment]
"인덱스 시그니처의 타입"과 "지정된 프로퍼티의 타입"이 일치하지 않기 때문입니다.
인덱스 시그너처의 경우 모든 키에 대해 값이 `string` 타입이어야 함을 명시하고 있지만, Web 프로퍼티의 값은 `number` 타입으로 지정되어 있습니다. 따라서 오류를 해결하기 위해서 둘의 타입을 호환될 수 있도록 해주어야 합니다. 

```ts
type SoptCodes = {
    [key: string]: string | number; // string 또는 number (둘다 가능하게!)
    Web: number;               
};
```

**Comment by thisishwarang** [comment]
인덱스 시그니처를 사용하여 정의한 타입은 key -> string, value -> string 이지만
직접 추가한 Web 프로퍼티의 value 타입은 number 이기 때문에 이 두가지가 일치하지 않아 에러가 발생합니다.

```ts
type SoptCodes = {
	[key: string]: string | number;
        Web: number;       
};
```

**Comment by heesunee** [comment]
`[key: string]: string;` 선언은 모든 키가 `string` 타입의 값을 가져야 한다는 뜻이지만, `Web` 속성에 `number` 타입을 사용하려 했기 때문에 오류가 발생합니다. 
따라서 number 타입 또한 사용할 수 있도록 해주어야 합니다.
```typeScript
type SoptCodes = {
  [key: string]: string | number;
  Web: number;
};
```

**Comment by yarimu** [comment]
`정답 및 풀이` 

1. 오류수정
    - 방법1_ Web 프로퍼티를 String 타입으로 변경 (교안버전)
        
        ```tsx
        type SoptCodes = {
        	[key: string]: string;
        	Web: string;        
        };
        ```
        
    - 방법2_Web 프로퍼티를 인덱스 시그니처와 별도로 선언 (유니온 타입)
    
      ```tsx
        type SoptCodes = {
                [key: string]: string | number;
        	Web: string;        
        };
        ```

 2. 에러 발생 원인
    
    <aside>
    
    인덱스 시그니처를 사용하면서 추가적인 프로퍼티를 정의할 때에는 인덱스 시그니처의 value타입과 직접 추가한 프로퍼티의 value 타입이 호환되거나 일치해야 하기 때문.
    
    </aside>
