### ISSUE TITLE
[2주차/박희선] 더 안전하게 타입을 처리하는 방법

### ISSUE THREAD

**Issue by heesunee** [SOPT-all/35-STUDY-WEB-PEACANG#7]
### 문제

❓ 타입스크립트에는 원하는 타입으로 **타입을 좁혀주는 역할**을 수행하는 연산자들이 있는데, 이를 **( )** 라고 부릅니다. 빈칸에 들어갈 용어를 적고, 그에 해당하는 연산자들이 (3개) 어떤 상황에서 사용하는지 간단히 설명해주세요.

A1. 빈칸에 들어갈 용어:

A2. 빈칸 용어의 연산자들(3개)에 대한 설명:

**Comment by gonn-i** [comment]
A1: 타입을 좁혀주는 역할을 수행하는 연산자들을, `타입가드` 라고 부릅니다! 
A2: 
1️⃣ typeof 타입가드 
일반적으로 사용하는 타입 가드 입니다. 조건문처럼 타입을 좁히는 표현 방식으로 사용됩니다.
```js
 if (typeof value === "number") {
    console.log(value.toFixed());
  } 
```
2️⃣ instanceof 타입가드
instanceof 를 사용하면 내장 클래스 타입을 보장할 수 있는 타입가드를 만들 수 있습니다. 단, 내장 클래스나 직접 만든 클래스에만 사용할 수 있습니다. 따라서, 직접만든 타입에는 사용될 수 없습니다.
```js
   if (value instanceof Date) {
    console.log(value.getTime());
  } 
```
3️⃣ in 타입 가드 
직접 만든 타입을 좁혀주기 위해서 사용합니다
```js
   if (value && "age" in value){
    console.log(`${value.name}은 ${value.age}살 입니다`)
  } 
```

**Comment by gwagjiug** [comment]
A1. 빈칸에 들어갈 용어: 타입 가드입니다

A2. 빈칸 용어의 연산자들(3개)에 대한 설명: 

1. typeof 타입가드 : 일반적으로 사용하는 타입가드입니다.
2. instanceof 타입가드 : 이 타입가드를 사용하면 내장 클래스 타입을 보장할 수 있는 타입가드를 만들 수 있습니다. 단 직접 만든 클래스 또는 내장 클래스에만 사용이 가능한 연산입니다. 그래서 저희가 직접 만든 타입과 함께 사용할 수 없습니다.
3. in 타입 가드 : 직접 만든 타입과 함께 사용하려면 in 연산자를 이용해야 합니다.

**Comment by thisishwarang** [comment]
1. 타입가드
2. typeof : 특정 변수 혹은 함수의 매개변수에 대한 타입을 확인하여 타입을 좁혀준다.
instanceof : instanceof 연산자을 기준으로 왼쪽의 값이 오른쪽 클래스의 인스턴스인지 확인하는 연산자.
in : 개발자가 직접 만든 특정 타입과 같은 것들은 자바스크립트 클래스가 아니기 때문에 instanceof 연산자를 사용할 수 없다. 때문에 in 연산자를 사용하여 타입을 좁힐 수 있다.

**Comment by yarimu** [comment]
A1. 타입가드
A2

- typeof 연산자
: 변수의 타입이 기본타입인지 확인할때 주로 사용되며 조건문의 형태로 활용된다.
- instanceof 연산자
: 내장 클래스 타입을 보장할 수 있는 타입가드를 만들 수 있다. 즉 객체가 특정 클래스의 인스턴스인지 확인할 때 활용한다.
- in타입 가드
: 객체가 특정 속성을 가지고 있는 확인하여 타입을 좁힐 때 활용된다.

**Comment by heesunee** [comment]
# 정답
A1. 빈칸에 들어갈 용어: 타입 가드

A2. 빈칸 용어의 연산자들(3개)에 대한 설명:

typeof: typeof 연산자는 변수 또는 값의 타입을 반환합니다. 따라서 조건문과 함께 사용해 타입을 좁힙니다. 주로 기본 데이터 타입을 확인할 때 사용합니다

instanceof: 내장 클래스 또는 직접 만든 클래스에 사용이 가능한 타입가드 입니다

in: 직접 만든 타입과 함께 사용하는 타입가드 입니다.
