### ISSUE TITLE
[2주차/임화랑] 타입 좁히기의 다양한 연산자 

### ISSUE THREAD

**Issue by thisishwarang** [SOPT-all/35-STUDY-WEB-PEACANG#9]
### 문제

```ts
type Person = {
  name: string;
  age: number;
};

function func1(value: Date | null | Person) {
  if (typeof value === "object") {
    console.log(value.getTime());
  }
}

function func2(value: Date | null | Person) {
  if (value instanceof Person) {
    console.log(value);
  }
}
```

위 코드에서 func1, func2 함수에서 각각 에러가 발생하고 있다.
문제 1. 어디서 에러가 발생하는가?
문제 2. 왜 에러가 나는가?
문제 3. 에러를 해결하기 위해 어떻게 수정해야 하는가?

**Comment by gonn-i** [comment]
A1 : 

```ts
function func1(value: Date | null | Person) {
  if (typeof value === "object") { // 오류 발생 원인 🔥
    console.log(value.getTime());  // 오류 발생! 👀
  }
}
```

타입 좁히기에서는 객체 타입으로 조건문을 걸어주고 있는데, **getTime()은 Date 만이 getTime 메소드를 사용할 수 있기 떄문에** 오류가 발생하고 있습니다. 따라서, 아래와 같이 수정해주어야 합니다.

```ts
function func1(value: Date | null | Person) {
  if (value instanceof Date) {   // 변경된 부분 💡
    console.log(value.getTime());
  }
}
```

---
A2 : 

```ts
function func2(value: Date | null | Person) {
  if (value instanceof Person) { // 오류 발생 원인 🔥
    console.log(value);   // 오류 발생! 👀
  }
}
```
instanceof 타입가드의 경우, 내장 클래스나 직접 만든 클래스에만 사용 가능하기 때문에 직접 만든 타입에는 사용될 수 없다. 따라서 in 연산자로 바꿔주어야 한다! 

```ts
function func2(value: Date | null | Person) {
 if (value && "name" in value && "age" in value)  {   // 변경된 부분 💡
    console.log(value);   
  }
}```

**Comment by gwagjiug** [comment]
* func1 함수에서 console.log 부분에서 오류가 발생합니다
* func2 함수에서 `if (value instanceof Person)` 부분에서 오류가 발생합니다.

### 왜??

1. value의 타입이 `Date | null | Person` 이므로, `typeof value === object` 조건을 만족해도 Date 객체라고 확신할 수 없게 됩니다.

getTime() 메서드는 Date 객체에만 존재하는 메서드이기 때문에 Person 타입이나 null 일 경우 getTime() 메서드를 호출하려고 하면 에러가 발생하는 것입니다.

2. `value instanceof Person` 구문에서 Person 타입은 사용자 정의 타입으로 정의된 객체이므로 클래스가 아니다. 그래서 instanceof 구문을 사용하지 못하는 것

instanceof 연산자는 클래스 타입에서만 사용가능하며, 타입 별칭인  Person 에는 사용할 수 없다 

### 에러 해결 방안

```typescript
function func1(value: Date | null | Person) {
  if (value instanceof Date) {
    console.log(value.getTime());
  }
}
```

1. value 가 Date 객체인지 검사해야 하므로 instance of Date 조건을 사용해서 value 가 실제로 Date 타입일 때만 메서드를 호출하도록 수정

```typescript
function func2(value: Date | null | Person) {
  if (value && "name" in value && "age" in value) {
    console.log(value);
  }
}
```

2. value 가 Person 타입인지 확인하기 위해서 instanceof 대신 타입가드를 사용해서  Person 타입의 속성 `name` 과 `age` 가 존재하는 지 확인해야 합니다.

**Comment by heesunee** [comment]
A1. 어디서 에러가 발생하는가?
```typescript
function func1(value: Date | null | Person) {
  if (typeof value === "object") {
    console.log(value.getTime()); // 오류 발생
  }
}
```

```typescript
function func2(value: Date | null | Person) {
  if (value instanceof Person) { // 오류 발생
    console.log(value);
  }
}
```

A2. 에러 발생 이유

첫번째 오류의 경우, 조건문 내부에서 value의 값을 object 타입으로 좁히고 있지만, object 타입은 Date, null, Person을 모두 포함하고 있어 타입스크립트는 value를 Date로 판단하지 않습니다. 그런데 getTime() 메서드는 Date 객체에만 존재하므로 타입스크립트는 getTime()을 호출할 때 에러가 발생합니다.

두번째 오류의 경우 타입을 좁히는 조건문 내부에서 에러가 발생합니다. instanceof는 내장 클래스 또는 직접만든 클래스에만 사용이 가능한 연산입니다. 따라서 직접 정의한 타입 Person과 함께 사용할 수 없습니다.

A3. 에러 수정

```typescript
function func1(value: Date | null | Person) {
  if ( value instanceof Date) { //내장 클래스 타입을 보장하는 타입가드를 사용합니다.
    console.log(value.getTime()); 
  }
}
```

```typescript
function func2(value: Date | null | Person) {
  if (value && "name" in value && "age" in value) {  // 직접 만든 타입과 함께 사용하는 in 연산자를 사용합니다
    console.log(value);
  }
}

**Comment by yarimu** [comment]
```javascript
type Person = {
  name: string;
  age: number;
};

function func1(value: Date | null | Person) {
  if (typeof value === "object") {
    console.log(value.getTime());       // 오류발생!
  }
}

function func2(value: Date | null | Person) {
  if (value instanceof Person) {         // 오류발생!
    console.log(value);
  }
}
```

🅰️ 오류 발생 원인
- func1
: value가 Date | null | Person 타입 중 하나일 수 있으므로 getTime() 메서드가 항상 존재한다고 보장할 수 없기 때문이다. "object"로 타입을 좁혔지만, 여전히 value가  Date | null | Person 중 확실하지 않아 getTime메서드를 사용할 수 없다.
- func2
: 타입스크립트에서 instanceof는 클래스로 만든 객체에 대해서만 타입 확인이 가능하기 때문이다.  Person은 타입이나 인터페이스일 뿐, 자바스크립트의 클래스가 아니므로 instanceof로 타입을 확인할 수 없다.

🅰️ 오류해결
```javascript
function func1(value: Date | null | Person) {
  if (value instanceof Date) {
    console.log(value.getTime());
  }
}
```


```javascript
function func2(value: Date | null | Person) {
  if (value && "name" in value && "age" in value) {
    console.log(value);
  }
}
```

**Comment by thisishwarang** [comment]
```ts
type Person = {
  name: string;
  age: number;
};

function func1(value: Date | null | Person) {
  if (typeof value === "object") {
    console.log(value.getTime()); // 에러발생
  }
}

function func2(value: Date | null | Person) {
  if (value instanceof Person) { // 에러발생
    console.log(value);
  }
}
```

- func1 에서의 에러 이유 : getTime() 메서드는 value의 타입이 Date일때 Date 객체에서 사용할 수 있는 메서드이다. 이를 타입 좁히기에서 object 타입으로만 한정지었는데, null 타입에 대해 typeof 연산자를 사용하면 마찬가지로 object가 나온다. 그렇기 때문에 value가 Date 또는 null이 될 수 있어서 getTime() 메서드를 사용하지 못하는 에러가 발생한다.
- func1 에러 해결 방법 : `typeof value === "object"` 으로의 타입 좁히기 대신 `value instanceof Date` 와 같은 방식으로 instanceof 연산자를 사용하면 value가 Date 클래스에 속할때만으로 타입을 좁힐 수 있다.

- func2 에서의 에러 이유 : Person 이라는 사용자가 지정한 타입에 대해 instanceof 연산자를 사용하여 타입 좁히기를 진행했는데 instanceof 연산자는 자바스크립트 클래스에 한정해서 사용할 수 있다. 하지만 Person 타입은 클래스가 아니기 때문에 에러가 발생한다.
- func2 에러 해결 방법 : `value instanceof Person` 으로의 타입 좁히기 대신 `value && "name" in value && "age" in value` 와 같은 방식으로 in 연산자를 사용하면 name, age 프로퍼티가 value 값에 있는지 확인할 수 있다. 또한 in 연산자의 뒤에는 null, undefined 타입이 올 수 없기 때문에 앞에서 value값이 있을때를 먼저 한정지을 수 있다.
